新增圖片以及部分動畫資料
ACGNTaiwan/Anime-List_fork pull request #10
Opened 2019-09-27 04:12 UTC by asdf3601a

2019-09-27 04:16 UTC, james58899 commented on anime-data/anime2019.10.json
> +        "season": null,
@gnehs 這樣可以嗎？

2019-09-27 04:16 UTC, james58899 requested changes
解衝突

2019-09-27 04:17 UTC, gnehs commented
不知道
你可以試試看啊

James58899 <notifications@github.com> 於 2019年9月27日 週五 12:16 寫道：

> *@james58899* commented on this pull request.
> ------------------------------
>
> In anime-data/anime2019.10.json
> <https://github.com/ACGNTaiwan/Anime-List/pull/10#discussion_r328907903>:
>
> > @@ -400,10 +400,10 @@
>
>          "nameInJpn": "かいじゅうステップ ワンダバダ",
>
>          "date": "9/27",
>
>          "time": "17:20",
>
> -        "carrier": "",
>
> -        "season": ,
>
> +        "carrier": "Original",
>
> +        "season": null,
>
>
> @gnehs <https://github.com/gnehs> 這樣可以嗎？
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ACGNTaiwan/Anime-List/pull/10?email_source=notifications&email_token=AD7R62F72IQZNVQ4WODVEH3QLWCJRA5CNFSM4I3BSNF2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCGD3QCI#pullrequestreview-294107145>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AD7R62EWBHA5AR2PW3GQ2Y3QLWCJRANCNFSM4I3BSNFQ>
> .
>

2019-09-27 04:24 UTC, asdf3601a commented on anime-data/anime2019.10.json
> +        "season": null,
這個部份我只是看到VSCode紅紅的不太開心所以補上去的(?)

2019-09-27 04:25 UTC, gnehs commented
為什麼 Season 不填 1 就好

2019-09-27 04:26 UTC, gnehs commented on anime-data/anime2019.10.json
> +        "season": null,
VSCode 紅紅的代表丟進去網站會炸掉

2019-09-27 04:27 UTC, gnehs commented on anime-data/anime2019.10.json
> +        "season": null,
為什麼你們不填 1 啦

2019-09-27 04:27 UTC, james58899 commented on anime-data/anime2019.10.json
> +        "season": null,
請先解衝突

2019-09-27 04:30 UTC, asdf3601a commented on anime-data/anime2019.10.json
> +        "season": null,
補null就不會紅紅的囉（#）只是依舊不知道會不會炸掉

2019-09-27 04:33 UTC, james58899 requested changes

2019-09-27 04:33 UTC, james58899 commented on anime-data/anime2019.10.json
> +        "season": null,
null

2019-09-27 04:33 UTC, james58899 commented on anime-data/anime2019.10.json
> +        "season": null,
null

2019-09-27 06:38 UTC, james58899 approved these changes

2019-09-28 04:09 UTC, asdf3601a commented
🤔 啥時候可以Merge啊，還是還有甚麼問題要修？

2019-09-28 04:09 UTC, closed without merging